openapi: 3.0.3
info:
  title: FDK metadata quality service
  description: A backend service that will assess metadata quality of datasets, dataservices, concepts
  version: '1.0'
  contact:
    name: Digitaliseringsdirektoratet
    url: 'https://digdir.no'
  license:
    name: License of API
    url: 'http://data.norge.no/nlod/no/2.0'
paths:
  /metadataquality:
    post:
      description: Creates a metadata quality assessment
      operationId: createMetadataQualityAssessment
      requestBody:
        description: a document, or reference, that contains metadata
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Document'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QualityAssessment'
components:
  schemas:
    Document:
      properties:
        documentReference:
          type: string
          format: uri
    QualityAssessment:
      properties:
        score:
          type: integer
