openapi: 3.0.3
info:
  title: FDK metadata quality service
  description: A backend service that will assess metadata quality of datasets, dataservices, concepts
  version: '1.0'
  contact:
    name: Digitaliseringsdirektoratet
    url: 'https://digdir.no'
  license:
    name: License of API
    url: 'http://data.norge.no/nlod/no/2.0'
paths:
  /assessment:
    post:
      description: Creates a metadata quality assessment
      operationId: createMetadataQualityAssessment
      requestBody:
        description: a document, or reference, that contains metadata
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Document'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QualityAssessment'
  /dimensions:
    get:
      description: Get a list of dimensions
      operationId: getDimensions
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dimension'
  /indicators:
    get:
      description: Get a list of indicators
      operationId: getIndicators
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Indicator'
components:
  schemas:
    Document:
      properties:
        documentReference:
          type: string
          format: uri
    QualityAssessment:
      properties:
        rating:
          type: integer
        ratingCategory:
          type: string
        dimensions:
          type: array
          items:
            properties:
              dimensionRef:
                type: string
              score:
                type: integer
              indicators:
                type: array
                items:
                  properties:
                    indicatorRef:
                      type: string
                    score:
                      type: integer
    Dimension:
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        indicators:
          type: array
          items:
            properties:
              indicatorRef:
                type: string
    Indicator:
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        metrics:
          type: string
        weight:
          type: integer
