openapi: 3.0.3
info:
  title: FDK metadata quality service
  description: A backend service that will assess metadata quality of datasets, dataservices, concepts
  version: '1.0'
  contact:
    name: Digitaliseringsdirektoratet
    url: 'https://digdir.no'
  license:
    name: License of API
    url: 'http://data.norge.no/nlod/no/2.0'
paths:
  /validation:
    post:
      description: Validates RDF graph and generates a validation report
      operationId: createValidationReport
      requestBody:
        description: An RDF graph
        content:
          text/turtle:
            schema:
              type: string
        required: true
      responses:
        200:
          description: OK
          content:
            text/turtle:
              schema:
                type: string
  /assessment:
    post:
      description: Creates a metadata quality assessment
      operationId: createMetadataQualityAssessment
      parameters:
        - in: query
          name: entityType
          required: true
          schema:
            $ref: '#/components/schemas/EntityType'
          description: Entity type of interest
      requestBody:
        description: An RDF graph
        content:
          text/turtle:
            schema:
              type: string
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Assessment'
  /assessment/catalog/rating:
    get:
      description: Returns metadata quality assessment rating of a given catalog
      operationId: getCatalogAssessmentRating
      parameters:
        - in: query
          name: catalogId
          required: false
          schema:
            type: string
          description: Catalog ID of interest
        - in: query
          name: catalogUri
          required: false
          schema:
            type: string
          description: Catalog URI of interest
        - in: query
          name: entityType
          required: true
          schema:
            $ref: '#/components/schemas/EntityType'
          description: Entity type of interest
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rating'
  /assessment/entity:
    get:
      description: Returns metadata quality assessment for a given entity
      operationId: getMetadataQualityAssessmentForEntity
      parameters:
        - in: query
          name: entityUri
          required: true
          schema:
            type: string
          description: Entity URI of interest
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Assessment'
  /assessment/entities:
    get:
      description: Returns metadata quality assessment for given entities
      operationId: getMetadataQualityAssessmentsForEntities
      parameters:
        - in: query
          name: entityUris
          required: true
          schema:
            type: string
          description: Comma-separated entity URIs of interest
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Assessment'
components:
  schemas:
    EntityType:
      type: string
      enum:
        - dataset
    Catalog:
      properties:
        id:
          type: string
        uri:
          type: string
    Entity:
      properties:
        uri:
          type: string
        type:
          $ref: '#/components/schemas/EntityType'
        catalog:
          $ref: '#/components/schemas/Catalog'
    RatingCategory:
      type: string
      enum:
        - excellent
        - good
        - sufficient
        - poor
    DimensionType:
      type: string
      enum:
        - findability
        - accessibility
    IndicatorType:
      type: string
      enum:
        - access_url
        - keyword
        - subject
    Rating:
      properties:
        score:
          type: integer
        maxScore:
          type: integer
        category:
          $ref: '#/components/schemas/RatingCategory'
    Dimension:
      properties:
        type:
          $ref: '#/components/schemas/DimensionType'
        rating:
          $ref: '#/components/schemas/Rating'
        indicators:
          type: array
          items:
            $ref: '#/components/schemas/Indicator'
    Indicator:
      properties:
        type:
          $ref: '#/components/schemas/IndicatorType'
        weight:
          type: integer
        conforms:
          type: boolean
    Assessment:
      properties:
        id:
          type: string
        entity:
          $ref: '#/components/schemas/Entity'
        rating:
          $ref: '#/components/schemas/Rating'
        dimensions:
          type: array
          items:
            $ref: '#/components/schemas/Dimension'
        updated:
          type: string
          format: date-time
