logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.apache.jena.riot: ERROR

spring:
  data:
    mongodb:
      authentication-database: admin
      database: metadata-quality-service
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      host: ${MONGO_HOST:mongodb}
      port: ${MONGO_PORT:27017}
  rabbitmq:
    host: ${RABBIT_HOST:rabbitmq}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
application:
  sparql-uri: ${FDK_SPARQL_SERVICE_URI:https://sparql.fellesdatakatalog.digdir.no}/fuseki/harvested/query

---

spring:
  config:
    activate:
      on-profile: develop,test,unit-integration
  data:
    mongodb:
      authentication-database: admin
      database: metadata-quality-service
      username: ${MONGO_USERNAME:admin}
      password: ${MONGO_PASSWORD:admin}
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
application:
  sparql-uri: ${FDK_SPARQL_SERVICE_URI:https://sparql.staging.fellesdatakatalog.digdir.no}/fuseki/harvested/query
